server {
  listen 80;
  server_name zeldapdv.internal.lab n8n.zeldapdv.internal.lab waha.zeldapdv.internal.lab;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl;
  server_name zeldapdv.internal.lab;
  add_header Cache-Control no-store always;
  ssl_certificate /etc/nginx/certs/zeldapdv.internal.lab.crt;
  ssl_certificate_key /etc/nginx/certs/zeldapdv.internal.lab.key;
  location / {
    proxy_pass http://restaurante-zeldapdv-crm:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Connection upgrade;
  }
}
server {
  listen 443 ssl;
  server_name n8n.zeldapdv.internal.lab;
  ssl_certificate /etc/nginx/certs/zeldapdv.internal.lab.crt;
  ssl_certificate_key /etc/nginx/certs/zeldapdv.internal.lab.key;
  location / {
    proxy_pass http://restaurante-zeldapdv-n8n:5678;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
  }
}
server {
  listen 443 ssl;
  server_name waha.zeldapdv.internal.lab;
  ssl_certificate /etc/nginx/certs/zeldapdv.internal.lab.crt;
  ssl_certificate_key /etc/nginx/certs/zeldapdv.internal.lab.key;
  location / {
    proxy_pass http://restaurante-zeldapdv-waha:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
  }
}


